ALTER TABLE incident_reports MODIFY COLUMN incident_type ENUM(
    'OTHER','PACKAGE_DAMAGED','RECIPIENT_NOT_AVAILABLE','RECIPIENT_REFUSED','SECURITY_ISSUE','WRONG_ADDRESS',
    'DAMAGED_PARCEL','LOST_PARCEL','COD_DISPUTE','CUSTOMER_CONFLICT','SAFETY_INCIDENT','VEHICLE_BREAKDOWN',
    'TRAFFIC_ACCIDENT','SYSTEM_ERROR','BARCODE_SCAN_ERROR','WRONG_ORDER_ASSIGNMENT','OFFICE_OPERATION_ISSUE',
    'DELIVERY_EXCEPTION','PICKUP_EXCEPTION','RETURN_EXCEPTION'
) NOT NULL;

UPDATE incident_reports SET incident_type = 'DELIVERY_EXCEPTION' WHERE incident_type = 'RECIPIENT_NOT_AVAILABLE';
UPDATE incident_reports SET incident_type = 'DELIVERY_EXCEPTION' WHERE incident_type = 'WRONG_ADDRESS';
UPDATE incident_reports SET incident_type = 'DAMAGED_PARCEL' WHERE incident_type = 'PACKAGE_DAMAGED';
UPDATE incident_reports SET incident_type = 'CUSTOMER_CONFLICT' WHERE incident_type = 'RECIPIENT_REFUSED';
UPDATE incident_reports SET incident_type = 'SAFETY_INCIDENT' WHERE incident_type = 'SECURITY_ISSUE';

ALTER TABLE incident_reports MODIFY COLUMN incident_type ENUM(
    'DAMAGED_PARCEL',
    'LOST_PARCEL',
    'COD_DISPUTE',
    'CUSTOMER_CONFLICT',
    'SAFETY_INCIDENT',
    'VEHICLE_BREAKDOWN',
    'TRAFFIC_ACCIDENT',
    'SYSTEM_ERROR',
    'BARCODE_SCAN_ERROR',
    'WRONG_ORDER_ASSIGNMENT',
    'OFFICE_OPERATION_ISSUE',
    'DELIVERY_EXCEPTION',
    'PICKUP_EXCEPTION',
    'RETURN_EXCEPTION',
    'OTHER'
) NOT NULL;

ALTER TABLE incident_reports MODIFY COLUMN order_id INTEGER NULL;
