package com.logistics.enums;

public enum IncidentType {
    DAMAGED_PARCEL,
    LOST_PARCEL,
    COD_DISPUTE,
    CUSTOMER_CONFLICT,
    SAFETY_INCIDENT,
    VEHICLE_BREAKDOWN,
    TRAFFIC_ACCIDENT,
    SYSTEM_ERROR,
    BARCODE_SCAN_ERROR,
    WRONG_ORDER_ASSIGNMENT,
    OFFICE_OPERATION_ISSUE,
    DELIVERY_EXCEPTION,
    PICKUP_EXCEPTION,
    RETURN_EXCEPTION,
    OTHER
}