package com.logistics.enums;

public enum OrderHistoryActionType {
    PENDING,
    READY_FOR_PICKUP,
    TRANSIT_TO_OFFICE,
    CONFIRMED,
    URGENT_PICKUP,
    PICKING_UP,
    PICKED_UP,
    PICKUP_FAILED_FINAL,
    IMPORTED,
    EXPORTED,
    AT_DEST_OFFICE,
    DELIVERING,
    DELIVERED,
    DELIVERY_RETRY,
    DELIVERY_FAILED_FINAL,
    RETURNING,
    RETURN_AT_ORIGIN_OFFICE,
    RETURN_DELIVERY_ASSIGNED,
    RETURN_RETRY,
    RETURN_FAILED_FINAL,
    RETURNED,
    CANCELLED,
    ASSIGNED_TO_DELIVERY_TRIP,
    ORDER_LOADED_ON_VEHICLE,
    DELIVERY_STARTED
}