package com.logistics.enums;

public enum OrderHistoryActionType {
    PENDING,
    READY_FOR_PICKUP,
    TRANSIT_TO_OFFICE,
    URGENT_PICKUP,
    PICKING_UP,
    PICKED_UP,
    IMPORTED,
    EXPORTED,
    AT_DEST_OFFICE,
    DELIVERING,
    DELIVERED,
    PARTIAL_DELIVERY,
    PARTIAL_RETURN,
    FAILED_DELIVERY,
    DELIVERY_RETRY,
    DELIVERY_FAILED_FINAL,
    RETURNING,
    RETURN_RETRY,
    RETURN_FAILED_FINAL,
    RETURNED,
    CANCELLED
}